### **Load Dataset**

In [2]:
import pandas as pd
import numpy as np

#### **Q1**

In [4]:
pd.__version__

'3.0.5'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

#### **Q2**

- How many records are in the dataset?

In [5]:
len(df)

10000

#### **Q3**

- How many fuel types are presented in the dataset?

In [7]:
df['fuel_type'].nunique()

3

In [9]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

#### **Q4**

- How many columns in the dataset have missing values?

In [10]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

#### **Q5**

- What's the maximum fuel efficiency of cars from Asia?

In [11]:
df.groupby('origin')['fuel_efficiency_mpg'].max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

#### **Q6**
- Find the median value of the horsepower column in the dataset.
- Next, calculate the most frequent value of the same horsepower column.
- Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
- Now, calculate the median value of horsepower once again.

In [12]:
df['horsepower'].median()

np.float64(254.0)

In [18]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [19]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

In [20]:
df['horsepower'].median()

np.float64(252.0)

In [21]:
df[df['horsepower'].isnull()]

Empty DataFrame
Columns: [model_year, origin, fuel_type, drivetrain, num_doors, engine_displacement, num_cylinders, horsepower, vehicle_weight, acceleration, fuel_efficiency_mpg]
Index: []

#### **Q7**

- Select all the cars from Asia
- Select only columns vehicle_weight and model_year
- Select the first 7 values
- Get the underlying NumPy array. Let's call it X.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Invert XTX.
- Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- What's the sum of all the elements of the result?

In [22]:
asia_df = df[df['origin'] == 'Asia']

In [23]:
asia_df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [24]:
len(asia_df)

2994

In [25]:
asia_df = asia_df[['vehicle_weight', 'model_year']]
asia_df.head()

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007

In [28]:
asia_df = asia_df.head(7)
asia_df

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [29]:
X = np.array(asia_df)
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [30]:
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [31]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [32]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [35]:
result = XTX_inv.dot(X.T)

In [37]:
w = result * y
w

array([[-0.27509119, -0.02155228, -0.22895733,  0.35996837, -1.18162927,
         1.21328359,  0.27042587],
       [ 0.67427208,  0.13904122,  0.5529994 , -0.71637186,  2.63152339,
        -2.54924935, -0.49946567]])